# Generated by Django 5.1.6 on 2025-02-22 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0002_servicerequest_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='attachment',
        ),
    ]
